apiVersion: batch/v1
kind: Job
metadata:
  name: mohsin-testing-ttl
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
